### ISSUE TITLE
running failed on Windows7

### ISSUE THREAD

**Issue by xray1111** [lloydmeta/scala-akka-cv-part2#4]
I cloned and compiled the project using sbt, but got an error when running it. I can see that the camera was turned on by the app because the light's up, but it couldn't capture the image (all the same if loading default custom haar cascade file or not).

D:\homework\akka\scala-akka-cv-part2>sbt run Java HotSpot(TM) Client VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
[info] Loading global plugins from C:\Users\XRay\.sbt\0.13\plugins
[info] Loading project definition from D:\homework\akka\scala-akka-cv-part2\project
[info] Set current project to scala-cv-part2 (in build file:/D:/homework/akka/scala-akka-cv-part2/)
[info] Running com.beachape.WebcamFaceDetector
[info] [ERROR] [02/04/2017 22:38:40.218] [default-akka.actor.default-dispatcher-5] [akka://default/user/$a] videoInput.setupDevice() Error: Could not setup device.
[info] org.bytedeco.javacv.FrameGrabber$Exception: videoInput.setupDevice() Error: Could not setup device.
[info]  at org.bytedeco.javacv.VideoInputFrameGrabber.start(VideoInputFrameGrabber.java:111)
[info]  at org.bytedeco.javacv.VideoInputFrameGrabber.start(VideoInputFrameGrabber.java:101)
[info]  at com.beachape.video.Webcam$.com$beachape$video$Webcam$$buildGrabber(Webcam.scala:61)
[info]  at com.beachape.video.Webcam$WebcamFramePublisher.grabber$lzycompute(Webcam.scala:79)
[info]  at com.beachape.video.Webcam$WebcamFramePublisher.grabber(Webcam.scala:79)
[info]  at com.beachape.video.Webcam$WebcamFramePublisher.grabFrame(Webcam.scala:107)
[info]  at com.beachape.video.Webcam$WebcamFramePublisher.com$beachape$video$Webcam$WebcamFramePublisher$$emitFrames(Webcam.scala:99)
[info]  at com.beachape.video.Webcam$WebcamFramePublisher$$anonfun$receive$1.applyOrElse(Webcam.scala:88)
[info]  at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
[info]  at com.beachape.video.Webcam$WebcamFramePublisher.akka$stream$actor$ActorPublisher$$super$aroundReceive(Webcam.scala:68)
[info]  at akka.stream.actor.ActorPublisher$class.aroundReceive(ActorPublisher.scala:270)
[info]  at com.beachape.video.Webcam$WebcamFramePublisher.aroundReceive(Webcam.scala:68)
[info]  at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
[info]  at akka.actor.ActorCell.invoke(ActorCell.scala:487)
[info]  at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
[info]  at akka.dispatch.Mailbox.run(Mailbox.scala:220)
[info]  at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
[info]  at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[info]  at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[info]  at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[info]  at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[info]

**Comment by lloydmeta** [comment]
This repo currently uses a very early version of the SBT OpenCV plugin, which in turn is still using a very old version of JavaCV. That version might have had some bugs w/ Windows that have since been fixed.

Can you try upgrading the plugin using [the latest](https://github.com/bytedeco/sbt-javacv#sbt-javacv) version?

Also, make sure to set the following to in `Build.scala`, perhaps [here](https://github.com/lloydmeta/scala-akka-cv-part2/blob/master/project/Build.scala#L14)

```scala
// Build.scala
javaCVVersion := "1.3.1",
javaCppVersion := "1.3.1"
```

**Comment by xray1111** [comment]
Hi, lloydmeta

I add a line to plugins.sbt which is fine:
addSbtPlugin("org.bytedeco" % "sbt-javacv" % "1.12")

but the other 2 lines seems illegal when added to Build.scala:
javaCVVersion := "1.3.1",
javaCppVersion := "1.3.1"

IDE reports a compiler error:
[error] D:\homework\akka\scala-akka-cv-part2\project\Build.scala:16: not found: value javaCVVersion
[error]         javaCVVersion := "1.3.1",
[error]         ^
[error] one error found
[error] (compile:compileIncremental) Compilation failed
Invalid response.

**Comment by lloydmeta** [comment]
Ah, you'll need to add the proper imports at the top

```scala
import org.bytedeco.sbt.javacv.Plugin.autoImport._
import org.bytedeco.sbt.javacpp.Plugin.autoImport._
```

**Comment by xray1111** [comment]
You mean add these two import lines at the top of Build.scala? 

import org.bytedeco.sbt.javacv.Plugin.autoImport._
import org.bytedeco.sbt.javacpp.Plugin.autoImport._

Still report error: "Can not resolve symble sbt", and the lines color is grey(invalid), maybe I should try it again under linux tomorrow...

**Comment by lloydmeta** [comment]
That's very strange, because that's the path for the sbt setting keys. Have you tried compiling from the command line?

**Comment by xray1111** [comment]
yes, and this is the output:

D:\homework\akka\scala-akka-cv-part2>sbt compile
Java HotSpot(TM) Client VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
[info] Loading global plugins from C:\Users\XRay\.sbt\0.13\plugins
[info] Loading project definition from D:\homework\akka\scala-akka-cv-part2\project
[info] Compiling 1 Scala source to D:\homework\akka\scala-akka-cv-part2\project\target\scala-2.10\sbt-0.13\classes...
java.lang.RuntimeException: Some keys were defined with the same name but different types: 'javaCppPlatform' (java.lang.String, scala.collection.Seq[java.lang.String])
        at scala.sys.package$.error(package.scala:27)
        at sbt.Index$.stringToKeyMap0(EvaluateConfigurations.scala:296)
        at sbt.Index$.stringToKeyMap(EvaluateConfigurations.scala:287)
        at sbt.Load$.structureIndex(Load.scala:180)
        at sbt.Load$.apply(Load.scala:137)
        at sbt.Load$.defaultLoad(Load.scala:36)
        at sbt.BuiltinCommands$.doLoadProject(Main.scala:481)
        at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:475)
        at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:475)
        at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
        at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
        at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
        at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
        at sbt.Command$.process(Command.scala:93)
        at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
        at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
        at sbt.State$$anon$1.process(State.scala:184)
        at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
        at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.MainLoop$.next(MainLoop.scala:98)
        at sbt.MainLoop$.run(MainLoop.scala:91)
        at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:70)
        at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:65)
        at sbt.Using.apply(Using.scala:24)
        at sbt.MainLoop$.runWithNewLog(MainLoop.scala:65)
        at sbt.MainLoop$.runAndClearLast(MainLoop.scala:48)
        at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:32)
        at sbt.MainLoop$.runLogged(MainLoop.scala:24)
        at sbt.StandardMain$.runManaged(Main.scala:53)
        at sbt.xMain.run(Main.scala:28)
        at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
        at xsbt.boot.Launch$.run(Launch.scala:109)
        at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
        at xsbt.boot.Launch$.launch(Launch.scala:117)
        at xsbt.boot.Launch$.apply(Launch.scala:18)
        at xsbt.boot.Boot$.runImpl(Boot.scala:41)
        at xsbt.boot.Boot$.main(Boot.scala:17)
        at xsbt.boot.Boot.main(Boot.scala)
[error] Some keys were defined with the same name but different types: 'javaCppPlatform' (java.lang.String, scala.collection.Seq[java.lang.String])
[error] Use 'last' for the full log.

**Comment by lloydmeta** [comment]
```
java.lang.RuntimeException: Some keys were defined with the same name but different types: 'javaCppPlatform' (java.lang.String, scala.collection.Seq[java.lang.String])
```

That's a strange error; I think you may have 2 different versions of the same plugin installed. 

Can you show me your plugins.sbt?

**Comment by xray1111** [comment]
**this is in my plugins.sbt:**

resolvers += Resolver.sonatypeRepo("releases")

addSbtPlugin("org.scalariform" % "sbt-scalariform" % "1.6.0")

addSbtPlugin("com.beachape" % "sbt-opencv" % "1.5")

addSbtPlugin("org.bytedeco" % "sbt-javacv" % "1.12")

**Comment by xray1111** [comment]
**Now I switch to ubuntu 16.04 without changing anything, and it WORKS! but only for a while, then it prompts another exception** **and the camera can't capture the image no more.**

**this is the error message right after I run it, but it seems ok, the camera can catch my face, no problem:**

[error] VIDEOIO ERROR: V4L/V4L2: VIDIOC_S_CROP
[error] VIDEOIO ERROR: V4L: setting property #9 is not supported
[error] VIDEOIO ERROR: V4L/V4L2: VIDIOC_S_CROP
[error] VIDEOIO ERROR: V4L: setting property #9 is not supported
[error] VIDEOIO ERROR: V4L: setting property #16 is not supported

**But after a few while, maybe 20 secs or more, it corrupts. Any suggestions?:**

[error] Corrupt JPEG data: 6 extraneous bytes before marker 0xd5
[error] org.bytedeco.javacv.FrameGrabber$Exception: Failed to load class org.bytedeco.javacv.FlyCapture2FrameGrabber
[error] 	at org.bytedeco.javacv.FlyCapture2FrameGrabber.tryLoad(FlyCapture2FrameGrabber.java:118)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] 	at org.bytedeco.javacv.FrameGrabber.getDefault(FrameGrabber.java:59)
[error] 	at org.bytedeco.javacv.FrameGrabber.createDefault(FrameGrabber.java:118)
[error] 	at com.beachape.video.Webcam$.com$beachape$video$Webcam$$buildGrabber(Webcam.scala:56)
[error] 	at com.beachape.video.Webcam$WebcamFramePublisher.grabber$lzycompute(Webcam.scala:79)
[error] 	at com.beachape.video.Webcam$WebcamFramePublisher.grabber(Webcam.scala:79)
[error] 	at com.beachape.video.Webcam$WebcamFramePublisher.grabFrame(Webcam.scala:107)
[error] 	at com.beachape.video.Webcam$WebcamFramePublisher.com$beachape$video$Webcam$WebcamFramePublisher$$emitFrames(Webcam.scala:99)
[error] 	at com.beachape.video.Webcam$WebcamFramePublisher$$anonfun$receive$1.applyOrElse(Webcam.scala:88)
[error] 	at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
[error] 	at com.beachape.video.Webcam$WebcamFramePublisher.akka$stream$actor$ActorPublisher$$super$aroundReceive(Webcam.scala:68)
[error] 	at akka.stream.actor.ActorPublisher$class.aroundReceive(ActorPublisher.scala:270)
[error] 	at com.beachape.video.Webcam$WebcamFramePublisher.aroundReceive(Webcam.scala:68)
[error] 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
[error] 	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
[error] 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
[error] 	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
[error] 	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
[error] 	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[error] 	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[error] 	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[error] 	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[error] Caused by: java.lang.NoClassDefFoundError: org/bytedeco/javacpp/FlyCapture2
[error] 	at org.bytedeco.javacv.FlyCapture2FrameGrabber.tryLoad(FlyCapture2FrameGrabber.java:116)
[error] 	... 25 more
[error] Caused by: java.lang.ClassNotFoundException: org.bytedeco.javacpp.FlyCapture2
[error] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[error] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[error] 	... 26 more
[error] VIDEOIO ERROR: V4L2: Pixel format of incoming image is unsupported by OpenCV
[error] Unable to stop the stream.: 设备或资源忙
[error] Unable to stop the stream.: 错误的文件描述符
[error] VIDEOIO ERROR: V4L: device /dev/video0: Unable to query number of channels
[info] [ERROR] [02/05/2017 18:35:42.377] [default-akka.actor.default-dispatcher-5] [akka://default/user/$a] cvRetrieveFrame() Error: Could not retrieve frame. (Has start() been called?)
[info] org.bytedeco.javacv.FrameGrabber$Exception: cvRetrieveFrame() Error: Could not retrieve frame. (Has start() been called?)
[info] 	at org.bytedeco.javacv.OpenCVFrameGrabber.grab(OpenCVFrameGrabber.java:239)
[info] 	at com.beachape.video.Webcam$WebcamFramePublisher.grabFrame(Webcam.scala:107)
[info] 	at com.beachape.video.Webcam$WebcamFramePublisher.com$beachape$video$Webcam$WebcamFramePublisher$$emitFrames(Webcam.scala:99)
[info] 	at com.beachape.video.Webcam$WebcamFramePublisher$$anonfun$receive$1.applyOrElse(Webcam.scala:88)
[info] 	at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
[info] 	at com.beachape.video.Webcam$WebcamFramePublisher.akka$stream$actor$ActorPublisher$$super$aroundReceive(Webcam.scala:68)
[info] 	at akka.stream.actor.ActorPublisher$class.aroundReceive(ActorPublisher.scala:270)
[info] 	at com.beachape.video.Webcam$WebcamFramePublisher.aroundReceive(Webcam.scala:68)
[info] 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
[info] 	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
[info] 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
[info] 	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
[info] 	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
[info] 	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[info] 	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[info] 	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[info] 	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[info] 
[info] [ERROR] [02/05/2017 18:35:55.236] [default-akka.actor.default-dispatcher-3] [akka://default/user/$a] cvCreateCameraCapture() Error: Could not create camera capture.
[info] org.bytedeco.javacv.FrameGrabber$Exception: cvCreateCameraCapture() Error: Could not create camera capture.
[info] 	at org.bytedeco.javacv.OpenCVFrameGrabber.start(OpenCVFrameGrabber.java:179)
[info] 	at com.beachape.video.Webcam$.com$beachape$video$Webcam$$buildGrabber(Webcam.scala:61)
[info] 	at com.beachape.video.Webcam$WebcamFramePublisher.grabber$lzycompute(Webcam.scala:79)
[info] 	at com.beachape.video.Webcam$WebcamFramePublisher.grabber(Webcam.scala:79)
[info] 	at com.beachape.video.Webcam$WebcamFramePublisher.grabFrame(Webcam.scala:107)
[info] 	at com.beachape.video.Webcam$WebcamFramePublisher.com$beachape$video$Webcam$WebcamFramePublisher$$emitFrames(Webcam.scala:99)
[info] 	at com.beachape.video.Webcam$WebcamFramePublisher$$anonfun$receive$1.applyOrElse(Webcam.scala:89)
[info] 	at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
[info] 	at com.beachape.video.Webcam$WebcamFramePublisher.akka$stream$actor$ActorPublisher$$super$aroundReceive(Webcam.scala:68)
[info] 	at akka.stream.actor.ActorPublisher$class.aroundReceive(ActorPublisher.scala:309)
[info] 	at com.beachape.video.Webcam$WebcamFramePublisher.aroundReceive(Webcam.scala:68)
[info] 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
[info] 	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
[info] 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
[info] 	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
[info] 	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
[info] 	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[info] 	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[info] 	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[info] 	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[info]

**Comment by lloydmeta** [comment]
> this is in my plugins.sbt:

Ok, so definitely remove this line 

```scala
addSbtPlugin("com.beachape" % "sbt-opencv" % "1.5")
```

`sbt-javacv` is its replacement. After that you should be able to set `javaCvVersion` and `javaCppVersion` properly.

Let me know how that goes.

**Comment by xray1111** [comment]
**Now it can be compiled, but still have problems when running:**

```[info] Compiling 10 Scala sources to D:\homework\akka\scala-akka-cv-part2\target\scala-2.11\classes...
[success] Total time: 29 s, completed 2017-2-5 22:00:55
> run
[info] Running com.beachape.WebcamFaceDetector
[info] [ERROR] [02/05/2017 22:01:15.263] [default-akka.actor.default-dispatcher-6] [akka://default/user/$a] videoInput.getPixels() Error: Could not get pixels.
[info] org.bytedeco.javacv.FrameGrabber$Exception: videoInput.getPixels() Error: Could not get pixels.
[info]  at org.bytedeco.javacv.VideoInputFrameGrabber.grab(VideoInputFrameGrabber.java:171)
[info]  at com.beachape.video.Webcam$WebcamFramePublisher.grabFrame(Webcam.scala:107)
[info]  at com.beachape.video.Webcam$WebcamFramePublisher.com$beachape$video$Webcam$WebcamFramePublisher$$emitFrames(Webcam.scala:99)
[info]  at com.beachape.video.Webcam$WebcamFramePublisher$$anonfun$receive$1.applyOrElse(Webcam.scala:88)
[info]  at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
[info]  at com.beachape.video.Webcam$WebcamFramePublisher.akka$stream$actor$ActorPublisher$$super$aroundReceive(Webcam.scala:68)
[info]  at akka.stream.actor.ActorPublisher$class.aroundReceive(ActorPublisher.scala:270)
[info]  at com.beachape.video.Webcam$WebcamFramePublisher.aroundReceive(Webcam.scala:68)
[info]  at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
[info]  at akka.actor.ActorCell.invoke(ActorCell.scala:487)
[info]  at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
[info]  at akka.dispatch.Mailbox.run(Mailbox.scala:220)
[info]  at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
[info]  at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[info]  at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[info]  at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[info]  at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[info]

**Comment by lloydmeta** [comment]
> Now it can be compiled,

Progress! 

> have problems when running:

Strange, maybe the deviceId hardcoded on [this line](https://github.com/lloydmeta/scala-akka-cv-part2/blob/c88ecf538f9a7db5b7065bdef1167acc56e9436f/src/main/scala/com/beachape/WebcamFaceDetector.scala#L73) is wrong for your system?

It could also be that you might need to try different ways of instantiating the FrameGrabber for your system; take a look [here](https://github.com/lloydmeta/scala-akka-cv-part2/blob/c88ecf538f9a7db5b7065bdef1167acc56e9436f/src/main/scala/com/beachape/video/Webcam.scala#L56).

**Comment by xray1111** [comment]
**I applied the changes to the project under ubuntu, this time only one line of error information:**
```
xray@xray-ThinkPad-T500:~/homework/akka/scala-akka-cv-part1$ sbt run
[info] Loading project definition from /home/xray/homework/akka/scala-akka-cv-part1/project
[info] Compiling 1 Scala source to /home/xray/homework/akka/scala-akka-cv-part1/project/target/scala-2.10/sbt-0.13/classes...
[info] Set current project to scala-cv-part1 (in build file:/home/xray/homework/akka/scala-akka-cv-part1/)
[info] Compiling 5 Scala sources to /home/xray/homework/akka/scala-akka-cv-part1/target/scala-2.11/classes...
[info] Running com.beachape.WebcamWindow 
[error] VIDEOIO ERROR: V4L2: setting property #9 is not supported
```
**But the program still corrupts after 1 minute or so, it's OOM error, and every time this error happens, my laptop would stuck for a while:**
```
[error] Corrupt JPEG data: premature end of data segment
[error] Corrupt JPEG data: 4 extraneous bytes before marker 0xd9
[error] Corrupt JPEG data: premature end of data segment
[error] Uncaught error from thread [default-akka.actor.default-dispatcher-7] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[default]
[error] java.lang.OutOfMemoryError: Physical memory usage is too high: physicalBytes = 1G > maxPhysicalBytes = 1G
[error] 	at org.bytedeco.javacpp.Pointer.deallocator(Pointer.java:562)
[error] 	at org.bytedeco.javacpp.Pointer.init(Pointer.java:121)
[error] 	at org.bytedeco.javacpp.opencv_core$Mat.clone(Native Method)
[error] 	at com.beachape.transform.Flip$.horizontal(Flip.scala:18)
[error] 	at com.beachape.WebcamWindow$$anonfun$2.apply(WebcamWindow.scala:24)
[error] 	at com.beachape.WebcamWindow$$anonfun$2.apply(WebcamWindow.scala:24)
[error] 	at akka.stream.impl.fusing.Map.onPush(Ops.scala:27)
[error] 	at akka.stream.impl.fusing.Map.onPush(Ops.scala:26)
[error] 	at akka.stream.stage.AbstractStage$PushPullGraphLogic$$anon$1.onPush(Stage.scala:54)
[error] 	at akka.stream.impl.fusing.GraphInterpreter.processElement$1(GraphInterpreter.scala:575)
[error] 	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:586)
[error] 	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:533)
[error] 	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:445)
[error] 	at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:389)
[error] 	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:549)
[error] 	at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
[error] 	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:495)
[error] 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
[error] 	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
[error] 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
[error] 	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
[error] 	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
[error] 	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[error] 	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[error] 	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[error] 	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
		java.lang.RuntimeException: Nonzero exit code returned from runner: 255
	at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last compile:run for the full output.
[error] (compile:run) Nonzero exit code returned from runner: 255
[error] Total time: 285 s, completed 2017-2-5 22:55:43
```

**Comment by lloydmeta** [comment]
It looks like the default settings for capturing video from opencv don't work well with your web cam or the driver for your webcam. I suspect the incompatibility is causing corrupt data error.

You'll need to figure out how to set up the webcam for your system; I suspect you'll need to do more than just open a default FrameGrabber ([here](https://github.com/lloydmeta/scala-akka-cv-part2/blob/c88ecf538f9a7db5b7065bdef1167acc56e9436f/src/main/scala/com/beachape/video/Webcam.scala#L56)).

This issue in [opencv](https://github.com/opencv/opencv/issues/4355) might offer guidance.

As for the OOM error, it's entirely possible that this toy app leaks memory (though I can't see how) at the native level; I'm relying purely on the JavaCV and JavaCPP wrappers to clean up references for me. It looks like some users have run into the same issue with GC not happening or not happening fast enough if you don't call `.release()` on the Mats that are allocated (and I clone a lot of them "just in case").  See [here for details](http://stackoverflow.com/questions/21050499/memory-leak-from-iterating-opencv-frames).

That said, I've left mine on for very long periods and haven't encountered an OOM.

**Comment by xray1111** [comment]
Thanks a lot, pal!

I'm looking into it and see if I can help...
